[package]
name = "slime-genetic-alg-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.slime-genetic-alg]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.46.1"
default-features = false
