// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback:                       1
// Total number of exported functions:  15

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    slime_ownership
    (
        init => init
        setGeneScienceContractAddress => set_gene_science_contract_address_endpoint
        totalSupply => total_supply
        balanceOf => balance_of
        ownerOf => owner_of
        approve => approve
        transfer => transfer
        transfer_from => transfer_from
        tokensOfOwner => tokens_of_owner
        createGenZeroSlime => create_gen_zero_slime
        catchSlime => catch_slime
        getSlimeById => get_slime_by_id_endpoint
        canBreedWith => can_breed_with
        breedWith => breed_with
    )
}

multiversx_sc_wasm_adapter::async_callback! { slime_ownership }
